/**
 * AUTHORITATIVE CENTRAL SCHEMA — the single source of truth for what the
 * central PostgreSQL database must contain.
 *
 * This file is hand-maintained. It is intentionally NOT derived at runtime
 * from the local till schema: the till carries local-only bookkeeping
 * columns (is_synced, sync_status, last_error_at, …) and local-only tables
 * (sync_state, system_settings, transfers) that must
 * never be demanded of the central database.
 *
 * Bump CENTRAL_SCHEMA_VERSION whenever this definition changes. It is
 * independent of the app version and the local database version.
 *
 * Column classification:
 *   required — the central database must have it; drift if absent.
 *   optional — used by some flows; reported but never blocks.
 *   legacy   — kept for historical data; never repaired, never dropped.
 */
export const CENTRAL_SCHEMA_VERSION = 2;

export type CentralColumnClass = "required" | "optional" | "legacy";

export type CentralColumnSpec = {
  name: string;
  /** PostgreSQL type, or a full additive fragment ("text not null default ''"). */
  pgType: string;
  classification?: CentralColumnClass;
};

export type CentralIndexSpec = {
  name: string;
  /** Full idempotent CREATE INDEX statement. */
  sql: string;
  /** Only emitted when one of these columns had to be repaired. */
  dependsOnColumns: string[];
  /** When true the index is expected to exist at all times, not only after a repair. */
  always?: boolean;
};

/** A constraint the central database must carry (unique / check / foreign key). */
export type CentralConstraintSpec = {
  name: string;
  /** Body only — "unique (a, b)" or "check (qty >= 0)" or "foreign key ...". */
  definition: string;
};

/** A row-security policy the central database must carry. */
export type CentralPolicySpec = {
  name: string;
  /** Full idempotent CREATE POLICY statement. */
  sql: string;
};

/** A trigger the central database must carry. */
export type CentralTriggerSpec = {
  name: string;
  /** Full idempotent CREATE TRIGGER statement. */
  sql: string;
};

export type CentralTableSchema = {
  table: string;
  label: string;
  primaryKey: string;
  columns: CentralColumnSpec[];
  indexes?: CentralIndexSpec[];
  constraints?: CentralConstraintSpec[];
  triggers?: CentralTriggerSpec[];
  policies?: CentralPolicySpec[];
  /**
   * Whether row-level security must be enabled. Central tables hold business
   * data reachable through the Data API, so the default is yes.
   */
  rowSecurity?: boolean;
};

export const CENTRAL_SCHEMA: CentralTableSchema[] = [
  {
    table: "stores",
    label: "Branches",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "code", pgType: "text" },
      { name: "name", pgType: "text" },
      { name: "address", pgType: "text" },
      { name: "phone", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "group_id", pgType: "text" },
      { name: "row_version", pgType: "integer" },
      { name: "location_type", pgType: "text" },
      { name: "parent_id", pgType: "text" },
      { name: "is_central", pgType: "boolean" },
      { name: "building_name", pgType: "text" },
      { name: "floor_label", pgType: "text" },
      { name: "is_active", pgType: "boolean" },
      { name: "archived_at", pgType: "timestamptz" },
      { name: "is_primary_sub", pgType: "boolean" },
      { name: "private_catalogue", pgType: "boolean" },
      { name: "deleted_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "membership_tiers",
    label: "Membership tiers",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "name", pgType: "text" },
      { name: "discount_percentage", pgType: "numeric(9,4)" },
      { name: "points_multiplier", pgType: "numeric(9,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "deleted_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "products",
    label: "Products",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "barcode", pgType: "text" },
      { name: "name", pgType: "text" },
      { name: "category", pgType: "text" },
      { name: "cost_price", pgType: "numeric(18,4)" },
      { name: "selling_price", pgType: "numeric(18,4)" },
      { name: "ecom_price", pgType: "numeric(18,4)" },
      { name: "stock_quantity", pgType: "integer" },
      { name: "custom_points", pgType: "numeric(18,4)" },
      { name: "point_multiplier", pgType: "numeric(9,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "sku", pgType: "text" },
      { name: "reorder_level", pgType: "integer" },
      { name: "tax_rate", pgType: "numeric(9,4)" },
      { name: "ecom_visible", pgType: "boolean" },
      { name: "stock_by_store", pgType: "jsonb" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "landing_pct", pgType: "numeric(18,4)" },
      { name: "sub_category", pgType: "text" },
      { name: "unit", pgType: "text" },
      { name: "packs", pgType: "jsonb" },
      { name: "barcode_aliases", pgType: "text[]" },
      { name: "is_archived", pgType: "boolean" },
      { name: "archived_at", pgType: "timestamptz" },
      { name: "brand", pgType: "text" },
      { name: "product_group", pgType: "text" },
      { name: "barcode_variants", pgType: "jsonb" },
      { name: "row_version", pgType: "integer" },
      { name: "deleted_at", pgType: "timestamptz" },
      { name: "owner_store_id", pgType: "text" },
    ],
  },
  {
    table: "product_barcodes",
    label: "Barcodes",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "product_id", pgType: "text" },
      { name: "barcode", pgType: "text" },
      { name: "label", pgType: "text" },
      { name: "pack_size", pgType: "numeric(18,4)" },
      { name: "is_primary", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "deleted_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "product_categories",
    label: "Categories",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "name", pgType: "text" },
      { name: "parent_id", pgType: "uuid" },
      { name: "sort", pgType: "integer" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "kind", pgType: "text" },
      { name: "row_version", pgType: "integer" },
      { name: "deleted_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "uom_units",
    label: "Units of measure",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "code", pgType: "text" },
      { name: "name", pgType: "text" },
      { name: "allow_decimal", pgType: "boolean" },
      { name: "sort", pgType: "integer" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "deleted_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "members",
    label: "Members",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "member_code", pgType: "text" },
      { name: "full_name", pgType: "text" },
      { name: "phone", pgType: "text" },
      { name: "email", pgType: "text" },
      { name: "address", pgType: "text" },
      { name: "date_of_birth", pgType: "date" },
      { name: "tier_id", pgType: "uuid" },
      { name: "loyalty_points", pgType: "numeric(18,4)" },
      { name: "total_spent", pgType: "numeric(18,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "is_verified", pgType: "boolean" },
      { name: "verified_at", pgType: "timestamptz" },
      { name: "verified_channel", pgType: "text" },
      { name: "membership_member_id", pgType: "uuid" },
      { name: "membership_revision", pgType: "bigint not null default 0" },
      { name: "membership_status", pgType: "text not null default 'active'" },
      { name: "deleted_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "promotions",
    label: "Promotions",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "title", pgType: "text" },
      { name: "promo_type", pgType: "text" },
      { name: "min_spend", pgType: "numeric(18,4)" },
      { name: "discount_percent", pgType: "numeric(9,4)" },
      { name: "discount_amount", pgType: "numeric(18,4)" },
      { name: "foc_product_id", pgType: "uuid" },
      { name: "points_per_dollar", pgType: "numeric(9,4)" },
      { name: "tier_rates", pgType: "jsonb" },
      { name: "is_active", pgType: "boolean" },
      { name: "start_date", pgType: "date" },
      { name: "end_date", pgType: "date" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "deleted_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "suppliers",
    label: "Suppliers",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "name", pgType: "text" },
      { name: "contact_name", pgType: "text" },
      { name: "phone", pgType: "text" },
      { name: "email", pgType: "text" },
      { name: "address", pgType: "text" },
      { name: "tax_number", pgType: "text" },
      { name: "notes", pgType: "text" },
      { name: "is_active", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "deleted_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "shifts",
    label: "Shifts",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "terminal_name", pgType: "text" },
      { name: "opened_by_name", pgType: "text" },
      { name: "opened_by_staff_id", pgType: "text" },
      { name: "opened_by_role", pgType: "text" },
      { name: "closed_by_name", pgType: "text" },
      { name: "closed_by_staff_id", pgType: "text" },
      { name: "closed_by_role", pgType: "text" },
      { name: "opened_at", pgType: "timestamptz" },
      { name: "closed_at", pgType: "timestamptz" },
      { name: "opening_float", pgType: "numeric(18,4)" },
      { name: "counted_cash", pgType: "numeric(18,4)" },
      { name: "expected_cash", pgType: "numeric(18,4)" },
      { name: "note", pgType: "text" },
      { name: "overdue", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "status", pgType: "text" },
      { name: "closing_float", pgType: "numeric(18,4)" },
      { name: "user_id", pgType: "uuid" },
      { name: "row_version", pgType: "integer" },
      { name: "counted_card", pgType: "numeric(18,4)" },
      { name: "counted_digital", pgType: "numeric(18,4)" },
      { name: "expected_card", pgType: "numeric(18,4)" },
      { name: "expected_digital", pgType: "numeric(18,4)" },
      { name: "variance_cash", pgType: "numeric(18,4)" },
      { name: "variance_card", pgType: "numeric(18,4)" },
      { name: "variance_digital", pgType: "numeric(18,4)" },
      { name: "variance_total", pgType: "numeric(18,4)" },
    ],
  },
  {
    table: "shift_notifications",
    label: "Shift summaries",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "shift_id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "store_name", pgType: "text" },
      { name: "terminal_name", pgType: "text" },
      { name: "closed_by", pgType: "text" },
      { name: "opened_at", pgType: "timestamptz" },
      { name: "closed_at", pgType: "timestamptz" },
      { name: "total_sales", pgType: "numeric" },
      { name: "transactions", pgType: "integer" },
      { name: "discounts", pgType: "numeric" },
      { name: "refunds", pgType: "numeric" },
      { name: "expected_cash", pgType: "numeric" },
      { name: "counted_cash", pgType: "numeric" },
      { name: "payment_breakdown", pgType: "jsonb" },
      { name: "summary", pgType: "text" },
      { name: "channels", pgType: "text[]" },
      { name: "created_at", pgType: "timestamptz" },
    ],
    indexes: [
      {
        name: "shift_notifications_store_closed_idx",
        sql: "CREATE INDEX IF NOT EXISTS shift_notifications_store_closed_idx ON public.shift_notifications (store_id, closed_at DESC);",
        dependsOnColumns: ["store_id", "closed_at"],
        always: true,
      },
    ],
    constraints: [
      { name: "shift_notifications_shift_key", definition: "unique (shift_id)" },
    ],
    policies: [
      {
        name: "Branch staff publish shift summaries",
        sql: "CREATE POLICY \"Branch staff publish shift summaries\" ON public.shift_notifications FOR INSERT TO authenticated WITH CHECK (public.is_staff_now() AND public.store_visible(store_id));",
      },
      {
        name: "Variance viewers read shift summaries",
        sql: "CREATE POLICY \"Variance viewers read shift summaries\" ON public.shift_notifications FOR SELECT TO authenticated USING (public.has_perm('can_shift_variance_view') AND public.store_visible(store_id));",
      },
    ],
  },
  {
    table: "shift_sessions",
    label: "Shift sessions",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "shift_id", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "terminal_name", pgType: "text" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "role", pgType: "text" },
      { name: "signed_in_at", pgType: "timestamptz" },
      { name: "signed_out_at", pgType: "timestamptz" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "shift_cash_counts",
    label: "Shift cash counts",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "shift_id", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "kind", pgType: "text" },
      { name: "counted_cash", pgType: "numeric(18,4)" },
      { name: "counted_card", pgType: "numeric(18,4)" },
      { name: "counted_digital", pgType: "numeric(18,4)" },
      { name: "reason", pgType: "text" },
      { name: "counted_by_name", pgType: "text" },
      { name: "counted_by_staff_id", pgType: "text" },
      { name: "counted_by_user_id", pgType: "uuid" },
      { name: "client_key", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "shift_close_events",
    label: "Shift close events",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "shift_id", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "event", pgType: "text" },
      { name: "from_state", pgType: "text" },
      { name: "to_state", pgType: "text" },
      { name: "detail", pgType: "text" },
      { name: "actor_name", pgType: "text" },
      { name: "actor_staff_id", pgType: "text" },
      { name: "actor_user_id", pgType: "uuid" },
      { name: "created_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "shift_reconciliations",
    label: "Shift reconciliations",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "shift_id", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "count_id", pgType: "text" },
      { name: "expected_cash", pgType: "numeric(18,4)" },
      { name: "expected_card", pgType: "numeric(18,4)" },
      { name: "expected_digital", pgType: "numeric(18,4)" },
      { name: "counted_cash", pgType: "numeric(18,4)" },
      { name: "counted_card", pgType: "numeric(18,4)" },
      { name: "counted_digital", pgType: "numeric(18,4)" },
      { name: "variance_cash", pgType: "numeric(18,4)" },
      { name: "variance_card", pgType: "numeric(18,4)" },
      { name: "variance_digital", pgType: "numeric(18,4)" },
      { name: "variance_total", pgType: "numeric(18,4)" },
      { name: "variance_status", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "shift_variance_alerts",
    label: "Shift variance alerts",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "shift_id", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "reconciliation_id", pgType: "text" },
      { name: "variance_total", pgType: "numeric(18,4)" },
      { name: "variance_status", pgType: "text" },
      { name: "severity", pgType: "text" },
      { name: "message", pgType: "text" },
      { name: "delivery_status", pgType: "text" },
      { name: "attempts", pgType: "integer" },
      { name: "last_error", pgType: "text" },
      { name: "last_attempt_at", pgType: "timestamptz" },
      { name: "acknowledged_at", pgType: "timestamptz" },
      { name: "acknowledged_by", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "drawer_events",
    label: "Drawer events",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "shift_id", pgType: "text" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "role", pgType: "text" },
      { name: "reason", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "approved_by", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "sales",
    label: "Sales",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "bill_number", pgType: "text" },
      { name: "member_id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "cashier_name", pgType: "text" },
      { name: "subtotal_amount", pgType: "numeric(18,4)" },
      { name: "total_amount", pgType: "numeric(18,4)" },
      { name: "discount_amount", pgType: "numeric(18,4)" },
      { name: "tax_amount", pgType: "numeric(18,4)" },
      { name: "payment_type", pgType: "text" },
      { name: "points_earned", pgType: "numeric(18,4)" },
      { name: "points_redeemed", pgType: "numeric(18,4)" },
      { name: "is_exchange", pgType: "boolean" },
      { name: "original_bill_number", pgType: "text" },
      { name: "is_refunded", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "shift_id", pgType: "text" },
      { name: "paid_amount", pgType: "numeric(18,4)" },
      { name: "change_amount", pgType: "numeric(18,4)" },
      { name: "exchange_credit", pgType: "numeric(18,4)" },
      { name: "exchanged_to_bill_number", pgType: "text" },
      { name: "coupon_code", pgType: "text" },
      { name: "coupon_promo_id", pgType: "text" },
      { name: "coupon_scope", pgType: "text" },
      { name: "coupon_discount", pgType: "numeric(18,4)" },
      { name: "rounding_adjustment", pgType: "numeric(18,4)" },
      { name: "rounding_label", pgType: "text" },
      { name: "payments", pgType: "jsonb" },
      { name: "client_transaction_id", pgType: "text", classification: "required" as const },
      { name: "cashier_id", pgType: "text" },
      { name: "created_by", pgType: "text" },
      { name: "updated_by", pgType: "text" },
      { name: "row_version", pgType: "integer" },
      { name: "store_name_snapshot", pgType: "text" },
      { name: "store_address_snapshot", pgType: "text" },
    ],
  },
  {
    table: "sale_items",
    label: "Sale items",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "sale_id", pgType: "uuid" },
      { name: "product_id", pgType: "uuid" },
      { name: "product_name", pgType: "text" },
      { name: "unit_price", pgType: "numeric(18,4)" },
      { name: "quantity", pgType: "integer" },
      { name: "discount_percent", pgType: "numeric(9,4)" },
      { name: "discount_amount", pgType: "numeric(18,4)" },
      { name: "is_return", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "tax_rate", pgType: "numeric(9,4)" },
      { name: "is_foc", pgType: "boolean" },
      { name: "promo_id", pgType: "text" },
      { name: "coupon_code", pgType: "text" },
      { name: "coupon_discount", pgType: "numeric(18,4)" },
      { name: "unit_cost", pgType: "numeric(18,4)" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "payment_transactions",
    label: "Payments",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "source_type", pgType: "text" },
      { name: "sale_id", pgType: "text" },
      { name: "booking_id", pgType: "text" },
      { name: "member_id", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "shift_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "amount", pgType: "numeric(18,4)" },
      { name: "method", pgType: "text" },
      { name: "kind", pgType: "text" },
      { name: "reference", pgType: "text" },
      { name: "cashier_id", pgType: "text" },
      { name: "cashier_name", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "paid_at", pgType: "timestamptz" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "status", pgType: "text" },
      { name: "metadata", pgType: "jsonb" },
      { name: "client_transaction_id", pgType: "text", classification: "required" as const },
    ],
    indexes: [
      {
        name: "payment_transactions_client_txn_idx",
        sql: 'create unique index if not exists "payment_transactions_client_txn_idx" on public.payment_transactions (client_transaction_id) where client_transaction_id is not null;',
        dependsOnColumns: ["client_transaction_id"],
      },
    ],
  },
  {
    table: "item_activity_logs",
    label: "Item activity",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "product_id", pgType: "text" },
      { name: "product_name", pgType: "text" },
      { name: "sku", pgType: "text" },
      { name: "barcode", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "activity_type", pgType: "text" },
      { name: "reference", pgType: "text" },
      { name: "quantity_delta", pgType: "integer" },
      { name: "stock_before", pgType: "integer" },
      { name: "stock_after", pgType: "integer" },
      { name: "unit_cost", pgType: "numeric(18,4)" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "role", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "purchase_orders",
    label: "Purchase orders",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "po_number", pgType: "text" },
      { name: "reference", pgType: "text" },
      { name: "supplier_name", pgType: "text" },
      { name: "operator_name", pgType: "text" },
      { name: "total_cost", pgType: "numeric(18,4)" },
      { name: "total_items_count", pgType: "integer" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "supplier_id", pgType: "uuid" },
      { name: "store_id", pgType: "text" },
      { name: "store_code", pgType: "text" },
      { name: "invoice_date", pgType: "date" },
      { name: "invoice_entry_date", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "status", pgType: "text" },
      { name: "pending_edit_request_id", pgType: "uuid" },
      { name: "pending_edit_by", pgType: "text" },
      { name: "pending_edit_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "purchase_order_items",
    label: "Purchase order items",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "po_id", pgType: "uuid" },
      { name: "product_id", pgType: "uuid" },
      { name: "barcode", pgType: "text" },
      { name: "product_name", pgType: "text" },
      { name: "cost_price", pgType: "numeric(18,4)" },
      { name: "selling_price", pgType: "numeric(18,4)" },
      { name: "quantity_received", pgType: "integer" },
      { name: "subtotal_cost", pgType: "numeric(18,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "sku", pgType: "text" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "bookings",
    label: "Bookings",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "ref", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "shift_id", pgType: "text" },
      { name: "customer_name", pgType: "text" },
      { name: "customer_phone", pgType: "text" },
      { name: "member_id", pgType: "uuid" },
      { name: "service_type_id", pgType: "text" },
      { name: "service_name", pgType: "text" },
      { name: "service_fee", pgType: "numeric(18,4)" },
      { name: "payment_timing", pgType: "text" },
      { name: "lines", pgType: "jsonb" },
      { name: "subtotal", pgType: "numeric(18,4)" },
      { name: "discount", pgType: "numeric(18,4)" },
      { name: "tax", pgType: "numeric(18,4)" },
      { name: "total", pgType: "numeric(18,4)" },
      { name: "paid", pgType: "numeric(18,4)" },
      { name: "due_date", pgType: "date" },
      { name: "note", pgType: "text" },
      { name: "cashier", pgType: "text" },
      { name: "status", pgType: "text" },
      { name: "sale_receipt_no", pgType: "text" },
      { name: "closed_at", pgType: "timestamptz" },
      { name: "racket_model", pgType: "text" },
      { name: "string_type", pgType: "text" },
      { name: "tension_main", pgType: "numeric(18,4)" },
      { name: "tension_cross", pgType: "numeric(18,4)" },
      { name: "tension_unit", pgType: "text" },
      { name: "grommet_notes", pgType: "text" },
      { name: "job_notes", pgType: "text" },
      { name: "dropped_off_at", pgType: "timestamptz" },
      { name: "promised_at", pgType: "timestamptz" },
      { name: "job_status", pgType: "text" },
      { name: "job_status_by", pgType: "text" },
      { name: "job_status_at", pgType: "timestamptz" },
      { name: "notify_whatsapp", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "tag_id", pgType: "text" },
      { name: "intake_note", pgType: "text" },
      { name: "string_origin", pgType: "text" },
      { name: "string_source_product_id", pgType: "uuid" },
      { name: "grip_product_id", pgType: "uuid" },
      { name: "charges", pgType: "jsonb" },
      { name: "technician", pgType: "text" },
      { name: "liability_accepted", pgType: "boolean" },
      { name: "incident_note", pgType: "text" },
      { name: "cancel_reason", pgType: "text" },
      { name: "cancelled_by", pgType: "text" },
      { name: "cancelled_at", pgType: "timestamptz" },
      { name: "cancelled_terminal", pgType: "text" },
      { name: "cancel_money_action", pgType: "text" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "booking_payments",
    label: "Booking payments",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "booking_id", pgType: "uuid" },
      { name: "amount", pgType: "numeric(18,4)" },
      { name: "method", pgType: "text" },
      { name: "cashier", pgType: "text" },
      { name: "paid_at", pgType: "timestamptz" },
      { name: "status", pgType: "text" },
      { name: "reference", pgType: "text" },
      { name: "client_payment_id", pgType: "text" },
      { name: "kind", pgType: "text" },
      { name: "refund_reason", pgType: "text" },
      { name: "refunds_payment_id", pgType: "uuid" },
      { name: "change_given", pgType: "numeric(18,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "stock_transfers",
    label: "Stock transfers",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "ref", pgType: "text" },
      { name: "kind", pgType: "text" },
      { name: "transfer_scope", pgType: "text" },
      { name: "from_store_id", pgType: "text" },
      { name: "from_store_name", pgType: "text" },
      { name: "from_group_id", pgType: "text" },
      { name: "to_store_id", pgType: "text" },
      { name: "to_store_name", pgType: "text" },
      { name: "to_group_id", pgType: "text" },
      { name: "status", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "created_by", pgType: "text" },
      { name: "approved_by", pgType: "text" },
      { name: "approved_at", pgType: "timestamptz" },
      { name: "received_by", pgType: "text" },
      { name: "received_at", pgType: "timestamptz" },
      { name: "rejected_reason", pgType: "text" },
      { name: "rejected_by", pgType: "text" },
      { name: "cancelled_reason", pgType: "text" },
      { name: "dispatched_by", pgType: "text" },
      { name: "dispatched_at", pgType: "timestamptz" },
      { name: "closed_at", pgType: "timestamptz" },
      { name: "fulfilment", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "stock_transfer_items",
    label: "Transfer items",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "transfer_id", pgType: "uuid" },
      { name: "product_id", pgType: "uuid" },
      { name: "barcode", pgType: "text" },
      { name: "sku", pgType: "text" },
      { name: "product_name", pgType: "text" },
      { name: "quantity", pgType: "integer" },
      { name: "quantity_approved", pgType: "integer" },
      { name: "quantity_dispatched", pgType: "integer" },
      { name: "quantity_received", pgType: "integer" },
      { name: "unit_cost", pgType: "numeric(18,4)" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "stock_adjustments",
    label: "Stock adjustments",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "product_id", pgType: "uuid" },
      { name: "product_name", pgType: "text" },
      { name: "sku", pgType: "text" },
      { name: "barcode", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "reason", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "previous_stock", pgType: "integer" },
      { name: "updated_stock", pgType: "integer" },
      { name: "delta", pgType: "integer" },
      { name: "cost_impact", pgType: "numeric(18,4)" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "role", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "draft_id", pgType: "uuid" },
      { name: "row_version", pgType: "integer" },
    ],
  },
  {
    table: "stock_count_drafts",
    label: "Stock count drafts",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "reference", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "store_code", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "staff_id", pgType: "text" },
      { name: "staff_name", pgType: "text" },
      { name: "status", pgType: "text" },
      { name: "reason", pgType: "text" },
      { name: "note", pgType: "text" },
      { name: "lines", pgType: "text" },
      { name: "line_count", pgType: "integer" },
      { name: "total_impact", pgType: "numeric(18,4)" },
      { name: "posted_at", pgType: "timestamptz" },
      { name: "posted_by", pgType: "text" },
      { name: "pending_edit_request_id", pgType: "uuid" },
      { name: "pending_edit_by", pgType: "text" },
      { name: "pending_edit_at", pgType: "timestamptz" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "authorization_actions",
    label: "Authorisation rules",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "action_key", pgType: "text" },
      { name: "scope_type", pgType: "text" },
      { name: "scope_id", pgType: "text" },
      { name: "mode", pgType: "text" },
      { name: "allowed_roles", pgType: "text[]" },
      { name: "allowed_user_ids", pgType: "text[]" },
      { name: "approval_timeout_minutes", pgType: "integer" },
      { name: "escalation_after_minutes", pgType: "integer" },
      { name: "escalation_roles", pgType: "text[]" },
      { name: "require_reason", pgType: "boolean" },
      { name: "threshold", pgType: "numeric(18,4)" },
      { name: "is_enabled", pgType: "boolean" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "authorization_requests",
    label: "Approval requests",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "action_key", pgType: "text" },
      { name: "requested_by", pgType: "text" },
      { name: "requested_by_name", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "reason", pgType: "text" },
      { name: "payload", pgType: "jsonb" },
      { name: "status", pgType: "text" },
      { name: "decided_by", pgType: "text" },
      { name: "decided_by_name", pgType: "text" },
      { name: "decided_at", pgType: "timestamptz" },
      { name: "decision_note", pgType: "text" },
      { name: "expires_at", pgType: "timestamptz" },
      { name: "consumed_at", pgType: "timestamptz" },
      { name: "requested_amount", pgType: "numeric" },
      { name: "approved_amount", pgType: "numeric" },
      { name: "approved_payload", pgType: "jsonb" },
      { name: "bill_snapshot", pgType: "jsonb" },
      { name: "snapshot_hash", pgType: "text" },
      { name: "held_order_id", pgType: "text" },
      { name: "notified_at", pgType: "timestamptz" },
      { name: "requester_direct_limit", pgType: "numeric" },
      { name: "value_unit", pgType: "text" },
      { name: "approval_route", pgType: "jsonb" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "authorization_log",
    label: "Authorisation log",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "action_key", pgType: "text" },
      { name: "mode_used", pgType: "text" },
      { name: "request_id", pgType: "uuid" },
      { name: "requested_by", pgType: "text" },
      { name: "authorized_by", pgType: "text" },
      { name: "authorizer_role", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "outcome", pgType: "text" },
      { name: "detail", pgType: "jsonb" },
      { name: "created_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "record_edits",
    label: "Posted record edit history",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "record_type", pgType: "text" },
      { name: "record_id", pgType: "text" },
      { name: "reference", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "terminal_id", pgType: "text" },
      { name: "action_key", pgType: "text" },
      { name: "request_id", pgType: "uuid" },
      { name: "edited_by", pgType: "text" },
      { name: "edited_by_name", pgType: "text" },
      { name: "authorized_by", pgType: "text" },
      { name: "authorized_by_name", pgType: "text" },
      { name: "mode_used", pgType: "text" },
      { name: "before_value", pgType: "jsonb" },
      { name: "after_value", pgType: "jsonb" },
      { name: "stock_deltas", pgType: "jsonb" },
      { name: "note", pgType: "text" },
      { name: "created_at", pgType: "timestamptz" },
    ],
  },
  {
    table: "held_orders",
    label: "Held orders",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "text" },
      { name: "label", pgType: "text" },
      { name: "store_id", pgType: "text" },
      { name: "shift_id", pgType: "text" },
      { name: "held_by", pgType: "text" },
      { name: "total", pgType: "numeric(18,4)" },
      { name: "lines", pgType: "jsonb" },
      { name: "cart_discount", pgType: "numeric(18,4)" },
      { name: "cart_discount_type", pgType: "text" },
      { name: "exchange_ref", pgType: "text" },
      { name: "member_id", pgType: "text" },
      { name: "member_name", pgType: "text" },
      { name: "coupon", pgType: "jsonb" },
      { name: "note", pgType: "text" },
      { name: "cancelled_from", pgType: "text" },
      { name: "held_at", pgType: "timestamptz" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "updated_at", pgType: "timestamptz" },
      { name: "row_version", pgType: "integer" },
      { name: "status", pgType: "text" },
      { name: "pending_request_id", pgType: "uuid" },
      { name: "bill_no", pgType: "text" },
      { name: "approval_snapshot_hash", pgType: "text" },
    ],
  },
  {
    table: "audit_logs",
    label: "Audit log",
    primaryKey: "id",
    columns: [
      { name: "id", pgType: "uuid" },
      { name: "user_name", pgType: "text" },
      { name: "action_category", pgType: "text" },
      { name: "action_name", pgType: "text" },
      { name: "target_module", pgType: "text" },
      { name: "details", pgType: "jsonb" },
      { name: "created_at", pgType: "timestamptz" },
      { name: "user_id", pgType: "text" },
      { name: "action", pgType: "text" },
      { name: "entity", pgType: "text" },
      { name: "before_state", pgType: "jsonb" },
      { name: "after_state", pgType: "jsonb" },
    ],
  },
  {
    table: "pos_settings",
    label: "POS settings",
    primaryKey: "id",
    columns: [{ name: "receipt_css", pgType: "text not null default ''" }],
  },
  {
    table: "pos_store_settings",
    label: "Branch settings",
    primaryKey: "id",
    columns: [
      { name: "require_pin_terminal_reset", pgType: "boolean" },
      { name: "row_version", pgType: "integer not null default 1" },
      { name: "updated_by", pgType: "text" },
    ],
  },
];

/** Fast lookup by table name (lowercase). */
export const CENTRAL_SCHEMA_BY_TABLE: ReadonlyMap<string, CentralTableSchema> = new Map(
  CENTRAL_SCHEMA.map((t) => [t.table, t]),
);
