/**
 * Bumps the patch digit of package.json and mirrors the version into every
 * committed version source used by the build.
 *
 * package.json is the authoritative application version. Historical release
 * tags may use a different numbering scheme and must not move the app version.
 *
 *   node scripts/bump-version.cjs          # bump package patch version
 *   node scripts/bump-version.cjs --write  # only re-sync generated version files
 *   node scripts/bump-version.cjs --set 1.2.3
 */
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const pkgPath = path.join(root, "package.json");
const lockPath = path.join(root, "package-lock.json");
const versionPath = path.join(root, "src", "version.ts");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const writeOnly = process.argv.includes("--write");
const setAt = process.argv.indexOf("--set");
const requested = setAt >= 0 ? process.argv[setAt + 1] : "";

function parseVersion(value) {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(String(value || ""));
  return match ? match.slice(1).map(Number) : null;
}

function syncLockVersion(version) {
  if (!fs.existsSync(lockPath)) return;
  const lock = JSON.parse(fs.readFileSync(lockPath, "utf8"));
  lock.version = version;
  if (lock.packages && lock.packages[""]) {
    lock.packages[""].version = version;
  }
  fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
}

if (requested) {
  if (!parseVersion(requested)) {
    throw new Error(`Invalid release version: ${requested}`);
  }
  pkg.version = requested;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
} else if (!writeOnly) {
  const [major = 1, minor = 0, patch = 0] = parseVersion(pkg.version) || [1, 0, 0];
  pkg.version = `${major}.${minor}.${patch + 1}`;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
}

syncLockVersion(pkg.version);

fs.writeFileSync(
  versionPath,
  `// Generated by scripts/bump-version.cjs — do not edit by hand.\nexport const APP_VERSION = "${pkg.version}";\n`,
);

// The standalone SQL installer embeds the app version too. Keep it aligned
// for both a PR-prepared release and the automatic main-branch bump.
const installerPath = path.join(root, "database", "sqlserver", "retail-pos-local-database.sql");
const installer = fs.readFileSync(installerPath, "utf8")
  .replace(/Application version: \d+\.\d+\.\d+/, `Application version: ${pkg.version}`)
  .replace(/N'\d+\.\d+\.\d+' AS application_version/, `N'${pkg.version}' AS application_version`)
  .replace(/PRINT N'Retail POS \d+\.\d+\.\d+:/, `PRINT N'Retail POS ${pkg.version}:`);
fs.writeFileSync(installerPath, installer);
process.stdout.write(`${pkg.version}\n`);
