/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AllShopsRouteImport } from './routes/all-shops'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatabaseStartupRouteImport } from './routes/database-startup'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as HoldsRouteImport } from './routes/holds'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InventoryHubRouteImport } from './routes/inventory-hub'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StockOperationsRouteImport } from './routes/stock-operations'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as VerificationsRouteImport } from './routes/verifications'
import { Route as ApiCashierLoginRouteImport } from './routes/api/cashier-login'
import { Route as CTokenSlugRouteImport } from './routes/c.$tokenSlug'
import { Route as ClaimCampaignSlugRouteImport } from './routes/claim.$campaignSlug'
import { Route as PosGeneralBookingRouteImport } from './routes/pos.general-booking'
import { Route as PosRacketServiceRouteImport } from './routes/pos.racket-service'
import { Route as ReceivingIndexRouteImport } from './routes/receiving.index'
import { Route as ReceivingIdRouteImport } from './routes/receiving.$id'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsActivityRouteImport } from './routes/reports.activity'
import { Route as ReportsAnalyticsRouteImport } from './routes/reports.analytics'
import { Route as ReportsBusinessRouteImport } from './routes/reports.business'
import { Route as ReportsCatalogRouteImport } from './routes/reports.catalog'
import { Route as ReportsCouponsRouteImport } from './routes/reports.coupons'
import { Route as ReportsHistoryRouteImport } from './routes/reports.history'
import { Route as ReportsItemsRouteImport } from './routes/reports.items'
import { Route as ReportsNotificationsRouteImport } from './routes/reports.notifications'
import { Route as ReportsPaymentsRouteImport } from './routes/reports.payments'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as ReportsStockRouteImport } from './routes/reports.stock'
import { Route as ReportsVoidsRouteImport } from './routes/reports.voids'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAccessRouteImport } from './routes/settings.access'
import { Route as SettingsAccountsRouteImport } from './routes/settings.accounts'
import { Route as SettingsBookingRulesRouteImport } from './routes/settings.booking-rules'
import { Route as SettingsBookingSlipRouteImport } from './routes/settings.booking-slip'
import { Route as SettingsBranchTelemetryRouteImport } from './routes/settings.branch-telemetry'
import { Route as SettingsCatalogRouteImport } from './routes/settings.catalog'
import { Route as SettingsDataSyncRouteImport } from './routes/settings.data-sync'
import { Route as SettingsDatabaseRouteImport } from './routes/settings.database'
import { Route as SettingsDatabaseExplorerRouteImport } from './routes/settings.database-explorer'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsDisplayRouteImport } from './routes/settings.display'
import { Route as SettingsElementsRouteImport } from './routes/settings.elements'
import { Route as SettingsGroupsRouteImport } from './routes/settings.groups'
import { Route as SettingsHardwareRouteImport } from './routes/settings.hardware'
import { Route as SettingsIdentityRouteImport } from './routes/settings.identity'
import { Route as SettingsInheritanceRouteImport } from './routes/settings.inheritance'
import { Route as SettingsLinesRouteImport } from './routes/settings.lines'
import { Route as SettingsLogicHealthRouteImport } from './routes/settings.logic-health'
import { Route as SettingsMobileTerminalsRouteImport } from './routes/settings.mobile-terminals'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsNumberingRouteImport } from './routes/settings.numbering'
import { Route as SettingsPaymentRouteImport } from './routes/settings.payment'
import { Route as SettingsPaymentMethodsRouteImport } from './routes/settings.payment-methods'
import { Route as SettingsPrinterRouteImport } from './routes/settings.printer'
import { Route as SettingsQrRouteImport } from './routes/settings.qr'
import { Route as SettingsReceiptDesignerRouteImport } from './routes/settings.receipt-designer'
import { Route as SettingsRegionRouteImport } from './routes/settings.region'
import { Route as SettingsRulesRouteImport } from './routes/settings.rules'
import { Route as SettingsSecurityAlertsRouteImport } from './routes/settings.security-alerts'
import { Route as SettingsServicesRouteImport } from './routes/settings.services'
import { Route as SettingsSessionsRouteImport } from './routes/settings.sessions'
import { Route as SettingsShiftAlertsRouteImport } from './routes/settings.shift-alerts'
import { Route as SettingsSkuRouteImport } from './routes/settings.sku'
import { Route as SettingsStockNumberingRouteImport } from './routes/settings.stock-numbering'
import { Route as SettingsSyncRouteImport } from './routes/settings.sync'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsTaxRouteImport } from './routes/settings.tax'
import { Route as SettingsTerminalsRouteImport } from './routes/settings.terminals'
import { Route as SettingsTypeRouteImport } from './routes/settings.type'
import { Route as SettingsUpdatesRouteImport } from './routes/settings.updates'
import { Route as SettingsVisibilityRouteImport } from './routes/settings.visibility'
import { Route as SettingsWhatsappRouteImport } from './routes/settings.whatsapp'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings.workspace'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as TransfersIdRouteImport } from './routes/transfers.$id'
import { Route as TransfersNewRouteImport } from './routes/transfers.new'
import { Route as ApiPublicCashierLoginRouteImport } from './routes/api/public/cashier-login'
import { Route as ApiPublicDesktopSessionRouteImport } from './routes/api/public/desktop-session'
import { Route as ApiPublicHealthMetadataRouteImport } from './routes/api/public/health-metadata'
import { Route as ApiPublicIdleTimeoutRouteImport } from './routes/api/public/idle-timeout'
import { Route as ApiPublicPosRulesRouteImport } from './routes/api/public/pos-rules'
import { Route as ApiPublicSecurityAlertsRouteImport } from './routes/api/public/security-alerts'
import { Route as ApiPublicStaffIdleTimeoutRouteImport } from './routes/api/public/staff-idle-timeout'
import { Route as ApiPublicSyncRouteImport } from './routes/api/public/sync'
import { Route as ApiPublicSyncHealthRouteImport } from './routes/api/public/sync-health'
import { Route as ApiPublicTerminalPairingRouteImport } from './routes/api/public/terminal-pairing'
import { Route as ApiPublicTerminalStaffRouteImport } from './routes/api/public/terminal-staff'
import { Route as ApiPublicPosRulesSaveRouteImport } from './routes/api/public/pos-rules.save'
import { Route as ApiV1PosActivityPreferencesRouteImport } from './routes/api/v1/pos/activity-preferences'
import { Route as ApiV1PosAuthorizationRouteImport } from './routes/api/v1/pos/authorization'
import { Route as ApiV1PosIpcAdoptRouteImport } from './routes/api/v1/pos/ipc-adopt'
import { Route as ApiV1PosIpcAuthorizeRouteImport } from './routes/api/v1/pos/ipc-authorize'
import { Route as ApiV1PosSyncRouteImport } from './routes/api/v1/pos/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AllShopsRoute = AllShopsRouteImport.update({
  id: '/all-shops',
  path: '/all-shops',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseStartupRoute = DatabaseStartupRouteImport.update({
  id: '/database-startup',
  path: '/database-startup',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldsRoute = HoldsRouteImport.update({
  id: '/holds',
  path: '/holds',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryHubRoute = InventoryHubRouteImport.update({
  id: '/inventory-hub',
  path: '/inventory-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StockOperationsRoute = StockOperationsRouteImport.update({
  id: '/stock-operations',
  path: '/stock-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationsRoute = VerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCashierLoginRoute = ApiCashierLoginRouteImport.update({
  id: '/api/cashier-login',
  path: '/api/cashier-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenSlugRoute = CTokenSlugRouteImport.update({
  id: '/c/$tokenSlug',
  path: '/c/$tokenSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimCampaignSlugRoute = ClaimCampaignSlugRouteImport.update({
  id: '/claim/$campaignSlug',
  path: '/claim/$campaignSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PosGeneralBookingRoute = PosGeneralBookingRouteImport.update({
  id: '/pos/general-booking',
  path: '/pos/general-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRacketServiceRoute = PosRacketServiceRouteImport.update({
  id: '/pos/racket-service',
  path: '/pos/racket-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingIndexRoute = ReceivingIndexRouteImport.update({
  id: '/receiving/',
  path: '/receiving/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingIdRoute = ReceivingIdRouteImport.update({
  id: '/receiving/$id',
  path: '/receiving/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsActivityRoute = ReportsActivityRouteImport.update({
  id: '/reports/activity',
  path: '/reports/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAnalyticsRoute = ReportsAnalyticsRouteImport.update({
  id: '/reports/analytics',
  path: '/reports/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsBusinessRoute = ReportsBusinessRouteImport.update({
  id: '/reports/business',
  path: '/reports/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCatalogRoute = ReportsCatalogRouteImport.update({
  id: '/reports/catalog',
  path: '/reports/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCouponsRoute = ReportsCouponsRouteImport.update({
  id: '/reports/coupons',
  path: '/reports/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsHistoryRoute = ReportsHistoryRouteImport.update({
  id: '/reports/history',
  path: '/reports/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsItemsRoute = ReportsItemsRouteImport.update({
  id: '/reports/items',
  path: '/reports/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsNotificationsRoute = ReportsNotificationsRouteImport.update({
  id: '/reports/notifications',
  path: '/reports/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPaymentsRoute = ReportsPaymentsRouteImport.update({
  id: '/reports/payments',
  path: '/reports/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStockRoute = ReportsStockRouteImport.update({
  id: '/reports/stock',
  path: '/reports/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsVoidsRoute = ReportsVoidsRouteImport.update({
  id: '/reports/voids',
  path: '/reports/voids',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessRoute = SettingsAccessRouteImport.update({
  id: '/settings/access',
  path: '/settings/access',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountsRoute = SettingsAccountsRouteImport.update({
  id: '/settings/accounts',
  path: '/settings/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBookingRulesRoute = SettingsBookingRulesRouteImport.update({
  id: '/settings/booking-rules',
  path: '/settings/booking-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBookingSlipRoute = SettingsBookingSlipRouteImport.update({
  id: '/settings/booking-slip',
  path: '/settings/booking-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBranchTelemetryRoute = SettingsBranchTelemetryRouteImport.update({
  id: '/settings/branch-telemetry',
  path: '/settings/branch-telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCatalogRoute = SettingsCatalogRouteImport.update({
  id: '/settings/catalog',
  path: '/settings/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDataSyncRoute = SettingsDataSyncRouteImport.update({
  id: '/settings/data-sync',
  path: '/settings/data-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDatabaseRoute = SettingsDatabaseRouteImport.update({
  id: '/settings/database',
  path: '/settings/database',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDatabaseExplorerRoute =
  SettingsDatabaseExplorerRouteImport.update({
    id: '/settings/database-explorer',
    path: '/settings/database-explorer',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/settings/diagnostics',
  path: '/settings/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDisplayRoute = SettingsDisplayRouteImport.update({
  id: '/settings/display',
  path: '/settings/display',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsElementsRoute = SettingsElementsRouteImport.update({
  id: '/settings/elements',
  path: '/settings/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGroupsRoute = SettingsGroupsRouteImport.update({
  id: '/settings/groups',
  path: '/settings/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHardwareRoute = SettingsHardwareRouteImport.update({
  id: '/settings/hardware',
  path: '/settings/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIdentityRoute = SettingsIdentityRouteImport.update({
  id: '/settings/identity',
  path: '/settings/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInheritanceRoute = SettingsInheritanceRouteImport.update({
  id: '/settings/inheritance',
  path: '/settings/inheritance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLinesRoute = SettingsLinesRouteImport.update({
  id: '/settings/lines',
  path: '/settings/lines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLogicHealthRoute = SettingsLogicHealthRouteImport.update({
  id: '/settings/logic-health',
  path: '/settings/logic-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMobileTerminalsRoute = SettingsMobileTerminalsRouteImport.update({
  id: '/settings/mobile-terminals',
  path: '/settings/mobile-terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNumberingRoute = SettingsNumberingRouteImport.update({
  id: '/settings/numbering',
  path: '/settings/numbering',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/settings/payment',
  path: '/settings/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPaymentMethodsRoute = SettingsPaymentMethodsRouteImport.update({
  id: '/settings/payment-methods',
  path: '/settings/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrinterRoute = SettingsPrinterRouteImport.update({
  id: '/settings/printer',
  path: '/settings/printer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsQrRoute = SettingsQrRouteImport.update({
  id: '/settings/qr',
  path: '/settings/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsReceiptDesignerRoute = SettingsReceiptDesignerRouteImport.update({
  id: '/settings/receipt-designer',
  path: '/settings/receipt-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRegionRoute = SettingsRegionRouteImport.update({
  id: '/settings/region',
  path: '/settings/region',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesRoute = SettingsRulesRouteImport.update({
  id: '/settings/rules',
  path: '/settings/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityAlertsRoute = SettingsSecurityAlertsRouteImport.update({
  id: '/settings/security-alerts',
  path: '/settings/security-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsServicesRoute = SettingsServicesRouteImport.update({
  id: '/settings/services',
  path: '/settings/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSessionsRoute = SettingsSessionsRouteImport.update({
  id: '/settings/sessions',
  path: '/settings/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShiftAlertsRoute = SettingsShiftAlertsRouteImport.update({
  id: '/settings/shift-alerts',
  path: '/settings/shift-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSkuRoute = SettingsSkuRouteImport.update({
  id: '/settings/sku',
  path: '/settings/sku',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStockNumberingRoute = SettingsStockNumberingRouteImport.update({
  id: '/settings/stock-numbering',
  path: '/settings/stock-numbering',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/settings/sync',
  path: '/settings/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTaxRoute = SettingsTaxRouteImport.update({
  id: '/settings/tax',
  path: '/settings/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTerminalsRoute = SettingsTerminalsRouteImport.update({
  id: '/settings/terminals',
  path: '/settings/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTypeRoute = SettingsTypeRouteImport.update({
  id: '/settings/type',
  path: '/settings/type',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUpdatesRoute = SettingsUpdatesRouteImport.update({
  id: '/settings/updates',
  path: '/settings/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVisibilityRoute = SettingsVisibilityRouteImport.update({
  id: '/settings/visibility',
  path: '/settings/visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWhatsappRoute = SettingsWhatsappRouteImport.update({
  id: '/settings/whatsapp',
  path: '/settings/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/settings/workspace',
  path: '/settings/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIdRoute = TransfersIdRouteImport.update({
  id: '/transfers/$id',
  path: '/transfers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersNewRoute = TransfersNewRouteImport.update({
  id: '/transfers/new',
  path: '/transfers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashierLoginRoute = ApiPublicCashierLoginRouteImport.update({
  id: '/api/public/cashier-login',
  path: '/api/public/cashier-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDesktopSessionRoute = ApiPublicDesktopSessionRouteImport.update({
  id: '/api/public/desktop-session',
  path: '/api/public/desktop-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthMetadataRoute = ApiPublicHealthMetadataRouteImport.update({
  id: '/api/public/health-metadata',
  path: '/api/public/health-metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIdleTimeoutRoute = ApiPublicIdleTimeoutRouteImport.update({
  id: '/api/public/idle-timeout',
  path: '/api/public/idle-timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPosRulesRoute = ApiPublicPosRulesRouteImport.update({
  id: '/api/public/pos-rules',
  path: '/api/public/pos-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSecurityAlertsRoute = ApiPublicSecurityAlertsRouteImport.update({
  id: '/api/public/security-alerts',
  path: '/api/public/security-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStaffIdleTimeoutRoute =
  ApiPublicStaffIdleTimeoutRouteImport.update({
    id: '/api/public/staff-idle-timeout',
    path: '/api/public/staff-idle-timeout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncRoute = ApiPublicSyncRouteImport.update({
  id: '/api/public/sync',
  path: '/api/public/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncHealthRoute = ApiPublicSyncHealthRouteImport.update({
  id: '/api/public/sync-health',
  path: '/api/public/sync-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTerminalPairingRoute =
  ApiPublicTerminalPairingRouteImport.update({
    id: '/api/public/terminal-pairing',
    path: '/api/public/terminal-pairing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTerminalStaffRoute = ApiPublicTerminalStaffRouteImport.update({
  id: '/api/public/terminal-staff',
  path: '/api/public/terminal-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPosRulesSaveRoute = ApiPublicPosRulesSaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => ApiPublicPosRulesRoute,
} as any)
const ApiV1PosActivityPreferencesRoute =
  ApiV1PosActivityPreferencesRouteImport.update({
    id: '/api/v1/pos/activity-preferences',
    path: '/api/v1/pos/activity-preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1PosAuthorizationRoute = ApiV1PosAuthorizationRouteImport.update({
  id: '/api/v1/pos/authorization',
  path: '/api/v1/pos/authorization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PosIpcAdoptRoute = ApiV1PosIpcAdoptRouteImport.update({
  id: '/api/v1/pos/ipc-adopt',
  path: '/api/v1/pos/ipc-adopt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PosIpcAuthorizeRoute = ApiV1PosIpcAuthorizeRouteImport.update({
  id: '/api/v1/pos/ipc-authorize',
  path: '/api/v1/pos/ipc-authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PosSyncRoute = ApiV1PosSyncRouteImport.update({
  id: '/api/v1/pos/sync',
  path: '/api/v1/pos/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/all-shops': typeof AllShopsRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/database-startup': typeof DatabaseStartupRoute
  '/display': typeof DisplayRoute
  '/holds': typeof HoldsRoute
  '/inventory': typeof InventoryRoute
  '/inventory-hub': typeof InventoryHubRoute
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/recovery': typeof RecoveryRoute
  '/sales': typeof SalesRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stock-operations': typeof StockOperationsRoute
  '/stores': typeof StoresRoute
  '/suppliers': typeof SuppliersRoute
  '/verifications': typeof VerificationsRoute
  '/api/cashier-login': typeof ApiCashierLoginRoute
  '/c/$tokenSlug': typeof CTokenSlugRoute
  '/claim/$campaignSlug': typeof ClaimCampaignSlugRoute
  '/pos/general-booking': typeof PosGeneralBookingRoute
  '/pos/racket-service': typeof PosRacketServiceRoute
  '/receiving/$id': typeof ReceivingIdRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/analytics': typeof ReportsAnalyticsRoute
  '/reports/business': typeof ReportsBusinessRoute
  '/reports/catalog': typeof ReportsCatalogRoute
  '/reports/coupons': typeof ReportsCouponsRoute
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/items': typeof ReportsItemsRoute
  '/reports/notifications': typeof ReportsNotificationsRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/reports/voids': typeof ReportsVoidsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/booking-rules': typeof SettingsBookingRulesRoute
  '/settings/booking-slip': typeof SettingsBookingSlipRoute
  '/settings/branch-telemetry': typeof SettingsBranchTelemetryRoute
  '/settings/catalog': typeof SettingsCatalogRoute
  '/settings/data-sync': typeof SettingsDataSyncRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/database-explorer': typeof SettingsDatabaseExplorerRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/elements': typeof SettingsElementsRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/settings/inheritance': typeof SettingsInheritanceRoute
  '/settings/lines': typeof SettingsLinesRoute
  '/settings/logic-health': typeof SettingsLogicHealthRoute
  '/settings/mobile-terminals': typeof SettingsMobileTerminalsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/numbering': typeof SettingsNumberingRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/printer': typeof SettingsPrinterRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/receipt-designer': typeof SettingsReceiptDesignerRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security-alerts': typeof SettingsSecurityAlertsRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/shift-alerts': typeof SettingsShiftAlertsRoute
  '/settings/sku': typeof SettingsSkuRoute
  '/settings/stock-numbering': typeof SettingsStockNumberingRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/tax': typeof SettingsTaxRoute
  '/settings/terminals': typeof SettingsTerminalsRoute
  '/settings/type': typeof SettingsTypeRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/settings/visibility': typeof SettingsVisibilityRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/receiving/': typeof ReceivingIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/api/public/cashier-login': typeof ApiPublicCashierLoginRoute
  '/api/public/desktop-session': typeof ApiPublicDesktopSessionRoute
  '/api/public/health-metadata': typeof ApiPublicHealthMetadataRoute
  '/api/public/idle-timeout': typeof ApiPublicIdleTimeoutRoute
  '/api/public/pos-rules': typeof ApiPublicPosRulesRouteWithChildren
  '/api/public/security-alerts': typeof ApiPublicSecurityAlertsRoute
  '/api/public/staff-idle-timeout': typeof ApiPublicStaffIdleTimeoutRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/public/sync-health': typeof ApiPublicSyncHealthRoute
  '/api/public/terminal-pairing': typeof ApiPublicTerminalPairingRoute
  '/api/public/terminal-staff': typeof ApiPublicTerminalStaffRoute
  '/api/public/pos-rules/save': typeof ApiPublicPosRulesSaveRoute
  '/api/v1/pos/activity-preferences': typeof ApiV1PosActivityPreferencesRoute
  '/api/v1/pos/authorization': typeof ApiV1PosAuthorizationRoute
  '/api/v1/pos/ipc-adopt': typeof ApiV1PosIpcAdoptRoute
  '/api/v1/pos/ipc-authorize': typeof ApiV1PosIpcAuthorizeRoute
  '/api/v1/pos/sync': typeof ApiV1PosSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/all-shops': typeof AllShopsRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/database-startup': typeof DatabaseStartupRoute
  '/display': typeof DisplayRoute
  '/holds': typeof HoldsRoute
  '/inventory': typeof InventoryRoute
  '/inventory-hub': typeof InventoryHubRoute
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/recovery': typeof RecoveryRoute
  '/sales': typeof SalesRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stock-operations': typeof StockOperationsRoute
  '/stores': typeof StoresRoute
  '/suppliers': typeof SuppliersRoute
  '/verifications': typeof VerificationsRoute
  '/api/cashier-login': typeof ApiCashierLoginRoute
  '/c/$tokenSlug': typeof CTokenSlugRoute
  '/claim/$campaignSlug': typeof ClaimCampaignSlugRoute
  '/pos/general-booking': typeof PosGeneralBookingRoute
  '/pos/racket-service': typeof PosRacketServiceRoute
  '/receiving/$id': typeof ReceivingIdRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/analytics': typeof ReportsAnalyticsRoute
  '/reports/business': typeof ReportsBusinessRoute
  '/reports/catalog': typeof ReportsCatalogRoute
  '/reports/coupons': typeof ReportsCouponsRoute
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/items': typeof ReportsItemsRoute
  '/reports/notifications': typeof ReportsNotificationsRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/reports/voids': typeof ReportsVoidsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/booking-rules': typeof SettingsBookingRulesRoute
  '/settings/booking-slip': typeof SettingsBookingSlipRoute
  '/settings/branch-telemetry': typeof SettingsBranchTelemetryRoute
  '/settings/catalog': typeof SettingsCatalogRoute
  '/settings/data-sync': typeof SettingsDataSyncRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/database-explorer': typeof SettingsDatabaseExplorerRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/elements': typeof SettingsElementsRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/settings/inheritance': typeof SettingsInheritanceRoute
  '/settings/lines': typeof SettingsLinesRoute
  '/settings/logic-health': typeof SettingsLogicHealthRoute
  '/settings/mobile-terminals': typeof SettingsMobileTerminalsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/numbering': typeof SettingsNumberingRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/printer': typeof SettingsPrinterRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/receipt-designer': typeof SettingsReceiptDesignerRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security-alerts': typeof SettingsSecurityAlertsRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/shift-alerts': typeof SettingsShiftAlertsRoute
  '/settings/sku': typeof SettingsSkuRoute
  '/settings/stock-numbering': typeof SettingsStockNumberingRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/tax': typeof SettingsTaxRoute
  '/settings/terminals': typeof SettingsTerminalsRoute
  '/settings/type': typeof SettingsTypeRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/settings/visibility': typeof SettingsVisibilityRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/receiving': typeof ReceivingIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transfers': typeof TransfersIndexRoute
  '/api/public/cashier-login': typeof ApiPublicCashierLoginRoute
  '/api/public/desktop-session': typeof ApiPublicDesktopSessionRoute
  '/api/public/health-metadata': typeof ApiPublicHealthMetadataRoute
  '/api/public/idle-timeout': typeof ApiPublicIdleTimeoutRoute
  '/api/public/pos-rules': typeof ApiPublicPosRulesRouteWithChildren
  '/api/public/security-alerts': typeof ApiPublicSecurityAlertsRoute
  '/api/public/staff-idle-timeout': typeof ApiPublicStaffIdleTimeoutRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/public/sync-health': typeof ApiPublicSyncHealthRoute
  '/api/public/terminal-pairing': typeof ApiPublicTerminalPairingRoute
  '/api/public/terminal-staff': typeof ApiPublicTerminalStaffRoute
  '/api/public/pos-rules/save': typeof ApiPublicPosRulesSaveRoute
  '/api/v1/pos/activity-preferences': typeof ApiV1PosActivityPreferencesRoute
  '/api/v1/pos/authorization': typeof ApiV1PosAuthorizationRoute
  '/api/v1/pos/ipc-adopt': typeof ApiV1PosIpcAdoptRoute
  '/api/v1/pos/ipc-authorize': typeof ApiV1PosIpcAuthorizeRoute
  '/api/v1/pos/sync': typeof ApiV1PosSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/all-shops': typeof AllShopsRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/database-startup': typeof DatabaseStartupRoute
  '/display': typeof DisplayRoute
  '/holds': typeof HoldsRoute
  '/inventory': typeof InventoryRoute
  '/inventory-hub': typeof InventoryHubRoute
  '/join': typeof JoinRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/promotions': typeof PromotionsRoute
  '/purchasing': typeof PurchasingRoute
  '/receipts': typeof ReceiptsRoute
  '/recovery': typeof RecoveryRoute
  '/sales': typeof SalesRoute
  '/shifts': typeof ShiftsRoute
  '/staff': typeof StaffRoute
  '/stock-operations': typeof StockOperationsRoute
  '/stores': typeof StoresRoute
  '/suppliers': typeof SuppliersRoute
  '/verifications': typeof VerificationsRoute
  '/api/cashier-login': typeof ApiCashierLoginRoute
  '/c/$tokenSlug': typeof CTokenSlugRoute
  '/claim/$campaignSlug': typeof ClaimCampaignSlugRoute
  '/pos/general-booking': typeof PosGeneralBookingRoute
  '/pos/racket-service': typeof PosRacketServiceRoute
  '/receiving/$id': typeof ReceivingIdRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/analytics': typeof ReportsAnalyticsRoute
  '/reports/business': typeof ReportsBusinessRoute
  '/reports/catalog': typeof ReportsCatalogRoute
  '/reports/coupons': typeof ReportsCouponsRoute
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/items': typeof ReportsItemsRoute
  '/reports/notifications': typeof ReportsNotificationsRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/reports/voids': typeof ReportsVoidsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/settings/access': typeof SettingsAccessRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/booking-rules': typeof SettingsBookingRulesRoute
  '/settings/booking-slip': typeof SettingsBookingSlipRoute
  '/settings/branch-telemetry': typeof SettingsBranchTelemetryRoute
  '/settings/catalog': typeof SettingsCatalogRoute
  '/settings/data-sync': typeof SettingsDataSyncRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/database-explorer': typeof SettingsDatabaseExplorerRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/display': typeof SettingsDisplayRoute
  '/settings/elements': typeof SettingsElementsRoute
  '/settings/groups': typeof SettingsGroupsRoute
  '/settings/hardware': typeof SettingsHardwareRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/settings/inheritance': typeof SettingsInheritanceRoute
  '/settings/lines': typeof SettingsLinesRoute
  '/settings/logic-health': typeof SettingsLogicHealthRoute
  '/settings/mobile-terminals': typeof SettingsMobileTerminalsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/numbering': typeof SettingsNumberingRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/printer': typeof SettingsPrinterRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/receipt-designer': typeof SettingsReceiptDesignerRoute
  '/settings/region': typeof SettingsRegionRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security-alerts': typeof SettingsSecurityAlertsRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/shift-alerts': typeof SettingsShiftAlertsRoute
  '/settings/sku': typeof SettingsSkuRoute
  '/settings/stock-numbering': typeof SettingsStockNumberingRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/tax': typeof SettingsTaxRoute
  '/settings/terminals': typeof SettingsTerminalsRoute
  '/settings/type': typeof SettingsTypeRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/settings/visibility': typeof SettingsVisibilityRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/transfers/new': typeof TransfersNewRoute
  '/receiving/': typeof ReceivingIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/api/public/cashier-login': typeof ApiPublicCashierLoginRoute
  '/api/public/desktop-session': typeof ApiPublicDesktopSessionRoute
  '/api/public/health-metadata': typeof ApiPublicHealthMetadataRoute
  '/api/public/idle-timeout': typeof ApiPublicIdleTimeoutRoute
  '/api/public/pos-rules': typeof ApiPublicPosRulesRouteWithChildren
  '/api/public/security-alerts': typeof ApiPublicSecurityAlertsRoute
  '/api/public/staff-idle-timeout': typeof ApiPublicStaffIdleTimeoutRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/public/sync-health': typeof ApiPublicSyncHealthRoute
  '/api/public/terminal-pairing': typeof ApiPublicTerminalPairingRoute
  '/api/public/terminal-staff': typeof ApiPublicTerminalStaffRoute
  '/api/public/pos-rules/save': typeof ApiPublicPosRulesSaveRoute
  '/api/v1/pos/activity-preferences': typeof ApiV1PosActivityPreferencesRoute
  '/api/v1/pos/authorization': typeof ApiV1PosAuthorizationRoute
  '/api/v1/pos/ipc-adopt': typeof ApiV1PosIpcAdoptRoute
  '/api/v1/pos/ipc-authorize': typeof ApiV1PosIpcAuthorizeRoute
  '/api/v1/pos/sync': typeof ApiV1PosSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/all-shops'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/bookings'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/database-startup'
    | '/display'
    | '/holds'
    | '/inventory'
    | '/inventory-hub'
    | '/join'
    | '/members'
    | '/membership'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/recovery'
    | '/sales'
    | '/shifts'
    | '/staff'
    | '/stock-operations'
    | '/stores'
    | '/suppliers'
    | '/verifications'
    | '/api/cashier-login'
    | '/c/$tokenSlug'
    | '/claim/$campaignSlug'
    | '/pos/general-booking'
    | '/pos/racket-service'
    | '/receiving/$id'
    | '/reports/activity'
    | '/reports/analytics'
    | '/reports/business'
    | '/reports/catalog'
    | '/reports/coupons'
    | '/reports/history'
    | '/reports/items'
    | '/reports/notifications'
    | '/reports/payments'
    | '/reports/sales'
    | '/reports/stock'
    | '/reports/voids'
    | '/requests/$id'
    | '/requests/new'
    | '/settings/access'
    | '/settings/accounts'
    | '/settings/booking-rules'
    | '/settings/booking-slip'
    | '/settings/branch-telemetry'
    | '/settings/catalog'
    | '/settings/data-sync'
    | '/settings/database'
    | '/settings/database-explorer'
    | '/settings/diagnostics'
    | '/settings/display'
    | '/settings/elements'
    | '/settings/groups'
    | '/settings/hardware'
    | '/settings/identity'
    | '/settings/inheritance'
    | '/settings/lines'
    | '/settings/logic-health'
    | '/settings/mobile-terminals'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payment'
    | '/settings/payment-methods'
    | '/settings/printer'
    | '/settings/qr'
    | '/settings/receipt-designer'
    | '/settings/region'
    | '/settings/rules'
    | '/settings/security-alerts'
    | '/settings/services'
    | '/settings/sessions'
    | '/settings/shift-alerts'
    | '/settings/sku'
    | '/settings/stock-numbering'
    | '/settings/sync'
    | '/settings/system'
    | '/settings/tax'
    | '/settings/terminals'
    | '/settings/type'
    | '/settings/updates'
    | '/settings/visibility'
    | '/settings/whatsapp'
    | '/settings/workspace'
    | '/transfers/$id'
    | '/transfers/new'
    | '/receiving/'
    | '/reports/'
    | '/requests/'
    | '/settings/'
    | '/transfers/'
    | '/api/public/cashier-login'
    | '/api/public/desktop-session'
    | '/api/public/health-metadata'
    | '/api/public/idle-timeout'
    | '/api/public/pos-rules'
    | '/api/public/security-alerts'
    | '/api/public/staff-idle-timeout'
    | '/api/public/sync'
    | '/api/public/sync-health'
    | '/api/public/terminal-pairing'
    | '/api/public/terminal-staff'
    | '/api/public/pos-rules/save'
    | '/api/v1/pos/activity-preferences'
    | '/api/v1/pos/authorization'
    | '/api/v1/pos/ipc-adopt'
    | '/api/v1/pos/ipc-authorize'
    | '/api/v1/pos/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/all-shops'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/bookings'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/database-startup'
    | '/display'
    | '/holds'
    | '/inventory'
    | '/inventory-hub'
    | '/join'
    | '/members'
    | '/membership'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/recovery'
    | '/sales'
    | '/shifts'
    | '/staff'
    | '/stock-operations'
    | '/stores'
    | '/suppliers'
    | '/verifications'
    | '/api/cashier-login'
    | '/c/$tokenSlug'
    | '/claim/$campaignSlug'
    | '/pos/general-booking'
    | '/pos/racket-service'
    | '/receiving/$id'
    | '/reports/activity'
    | '/reports/analytics'
    | '/reports/business'
    | '/reports/catalog'
    | '/reports/coupons'
    | '/reports/history'
    | '/reports/items'
    | '/reports/notifications'
    | '/reports/payments'
    | '/reports/sales'
    | '/reports/stock'
    | '/reports/voids'
    | '/requests/$id'
    | '/requests/new'
    | '/settings/access'
    | '/settings/accounts'
    | '/settings/booking-rules'
    | '/settings/booking-slip'
    | '/settings/branch-telemetry'
    | '/settings/catalog'
    | '/settings/data-sync'
    | '/settings/database'
    | '/settings/database-explorer'
    | '/settings/diagnostics'
    | '/settings/display'
    | '/settings/elements'
    | '/settings/groups'
    | '/settings/hardware'
    | '/settings/identity'
    | '/settings/inheritance'
    | '/settings/lines'
    | '/settings/logic-health'
    | '/settings/mobile-terminals'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payment'
    | '/settings/payment-methods'
    | '/settings/printer'
    | '/settings/qr'
    | '/settings/receipt-designer'
    | '/settings/region'
    | '/settings/rules'
    | '/settings/security-alerts'
    | '/settings/services'
    | '/settings/sessions'
    | '/settings/shift-alerts'
    | '/settings/sku'
    | '/settings/stock-numbering'
    | '/settings/sync'
    | '/settings/system'
    | '/settings/tax'
    | '/settings/terminals'
    | '/settings/type'
    | '/settings/updates'
    | '/settings/visibility'
    | '/settings/whatsapp'
    | '/settings/workspace'
    | '/transfers/$id'
    | '/transfers/new'
    | '/receiving'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/transfers'
    | '/api/public/cashier-login'
    | '/api/public/desktop-session'
    | '/api/public/health-metadata'
    | '/api/public/idle-timeout'
    | '/api/public/pos-rules'
    | '/api/public/security-alerts'
    | '/api/public/staff-idle-timeout'
    | '/api/public/sync'
    | '/api/public/sync-health'
    | '/api/public/terminal-pairing'
    | '/api/public/terminal-staff'
    | '/api/public/pos-rules/save'
    | '/api/v1/pos/activity-preferences'
    | '/api/v1/pos/authorization'
    | '/api/v1/pos/ipc-adopt'
    | '/api/v1/pos/ipc-authorize'
    | '/api/v1/pos/sync'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/all-shops'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/bookings'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/database-startup'
    | '/display'
    | '/holds'
    | '/inventory'
    | '/inventory-hub'
    | '/join'
    | '/members'
    | '/membership'
    | '/promotions'
    | '/purchasing'
    | '/receipts'
    | '/recovery'
    | '/sales'
    | '/shifts'
    | '/staff'
    | '/stock-operations'
    | '/stores'
    | '/suppliers'
    | '/verifications'
    | '/api/cashier-login'
    | '/c/$tokenSlug'
    | '/claim/$campaignSlug'
    | '/pos/general-booking'
    | '/pos/racket-service'
    | '/receiving/$id'
    | '/reports/activity'
    | '/reports/analytics'
    | '/reports/business'
    | '/reports/catalog'
    | '/reports/coupons'
    | '/reports/history'
    | '/reports/items'
    | '/reports/notifications'
    | '/reports/payments'
    | '/reports/sales'
    | '/reports/stock'
    | '/reports/voids'
    | '/requests/$id'
    | '/requests/new'
    | '/settings/access'
    | '/settings/accounts'
    | '/settings/booking-rules'
    | '/settings/booking-slip'
    | '/settings/branch-telemetry'
    | '/settings/catalog'
    | '/settings/data-sync'
    | '/settings/database'
    | '/settings/database-explorer'
    | '/settings/diagnostics'
    | '/settings/display'
    | '/settings/elements'
    | '/settings/groups'
    | '/settings/hardware'
    | '/settings/identity'
    | '/settings/inheritance'
    | '/settings/lines'
    | '/settings/logic-health'
    | '/settings/mobile-terminals'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payment'
    | '/settings/payment-methods'
    | '/settings/printer'
    | '/settings/qr'
    | '/settings/receipt-designer'
    | '/settings/region'
    | '/settings/rules'
    | '/settings/security-alerts'
    | '/settings/services'
    | '/settings/sessions'
    | '/settings/shift-alerts'
    | '/settings/sku'
    | '/settings/stock-numbering'
    | '/settings/sync'
    | '/settings/system'
    | '/settings/tax'
    | '/settings/terminals'
    | '/settings/type'
    | '/settings/updates'
    | '/settings/visibility'
    | '/settings/whatsapp'
    | '/settings/workspace'
    | '/transfers/$id'
    | '/transfers/new'
    | '/receiving/'
    | '/reports/'
    | '/requests/'
    | '/settings/'
    | '/transfers/'
    | '/api/public/cashier-login'
    | '/api/public/desktop-session'
    | '/api/public/health-metadata'
    | '/api/public/idle-timeout'
    | '/api/public/pos-rules'
    | '/api/public/security-alerts'
    | '/api/public/staff-idle-timeout'
    | '/api/public/sync'
    | '/api/public/sync-health'
    | '/api/public/terminal-pairing'
    | '/api/public/terminal-staff'
    | '/api/public/pos-rules/save'
    | '/api/v1/pos/activity-preferences'
    | '/api/v1/pos/authorization'
    | '/api/v1/pos/ipc-adopt'
    | '/api/v1/pos/ipc-authorize'
    | '/api/v1/pos/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AllShopsRoute: typeof AllShopsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BookingsRoute: typeof BookingsRoute
  CouponsRoute: typeof CouponsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DatabaseStartupRoute: typeof DatabaseStartupRoute
  DisplayRoute: typeof DisplayRoute
  HoldsRoute: typeof HoldsRoute
  InventoryRoute: typeof InventoryRoute
  InventoryHubRoute: typeof InventoryHubRoute
  JoinRoute: typeof JoinRoute
  MembersRoute: typeof MembersRoute
  MembershipRoute: typeof MembershipRoute
  PromotionsRoute: typeof PromotionsRoute
  PurchasingRoute: typeof PurchasingRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RecoveryRoute: typeof RecoveryRoute
  SalesRoute: typeof SalesRoute
  ShiftsRoute: typeof ShiftsRoute
  StaffRoute: typeof StaffRoute
  StockOperationsRoute: typeof StockOperationsRoute
  StoresRoute: typeof StoresRoute
  SuppliersRoute: typeof SuppliersRoute
  VerificationsRoute: typeof VerificationsRoute
  ApiCashierLoginRoute: typeof ApiCashierLoginRoute
  CTokenSlugRoute: typeof CTokenSlugRoute
  ClaimCampaignSlugRoute: typeof ClaimCampaignSlugRoute
  PosGeneralBookingRoute: typeof PosGeneralBookingRoute
  PosRacketServiceRoute: typeof PosRacketServiceRoute
  ReceivingIdRoute: typeof ReceivingIdRoute
  ReportsActivityRoute: typeof ReportsActivityRoute
  ReportsAnalyticsRoute: typeof ReportsAnalyticsRoute
  ReportsBusinessRoute: typeof ReportsBusinessRoute
  ReportsCatalogRoute: typeof ReportsCatalogRoute
  ReportsCouponsRoute: typeof ReportsCouponsRoute
  ReportsHistoryRoute: typeof ReportsHistoryRoute
  ReportsItemsRoute: typeof ReportsItemsRoute
  ReportsNotificationsRoute: typeof ReportsNotificationsRoute
  ReportsPaymentsRoute: typeof ReportsPaymentsRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  ReportsStockRoute: typeof ReportsStockRoute
  ReportsVoidsRoute: typeof ReportsVoidsRoute
  RequestsIdRoute: typeof RequestsIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  SettingsAccessRoute: typeof SettingsAccessRoute
  SettingsAccountsRoute: typeof SettingsAccountsRoute
  SettingsBookingRulesRoute: typeof SettingsBookingRulesRoute
  SettingsBookingSlipRoute: typeof SettingsBookingSlipRoute
  SettingsBranchTelemetryRoute: typeof SettingsBranchTelemetryRoute
  SettingsCatalogRoute: typeof SettingsCatalogRoute
  SettingsDataSyncRoute: typeof SettingsDataSyncRoute
  SettingsDatabaseRoute: typeof SettingsDatabaseRoute
  SettingsDatabaseExplorerRoute: typeof SettingsDatabaseExplorerRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsDisplayRoute: typeof SettingsDisplayRoute
  SettingsElementsRoute: typeof SettingsElementsRoute
  SettingsGroupsRoute: typeof SettingsGroupsRoute
  SettingsHardwareRoute: typeof SettingsHardwareRoute
  SettingsIdentityRoute: typeof SettingsIdentityRoute
  SettingsInheritanceRoute: typeof SettingsInheritanceRoute
  SettingsLinesRoute: typeof SettingsLinesRoute
  SettingsLogicHealthRoute: typeof SettingsLogicHealthRoute
  SettingsMobileTerminalsRoute: typeof SettingsMobileTerminalsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsNumberingRoute: typeof SettingsNumberingRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsPaymentMethodsRoute: typeof SettingsPaymentMethodsRoute
  SettingsPrinterRoute: typeof SettingsPrinterRoute
  SettingsQrRoute: typeof SettingsQrRoute
  SettingsReceiptDesignerRoute: typeof SettingsReceiptDesignerRoute
  SettingsRegionRoute: typeof SettingsRegionRoute
  SettingsRulesRoute: typeof SettingsRulesRoute
  SettingsSecurityAlertsRoute: typeof SettingsSecurityAlertsRoute
  SettingsServicesRoute: typeof SettingsServicesRoute
  SettingsSessionsRoute: typeof SettingsSessionsRoute
  SettingsShiftAlertsRoute: typeof SettingsShiftAlertsRoute
  SettingsSkuRoute: typeof SettingsSkuRoute
  SettingsStockNumberingRoute: typeof SettingsStockNumberingRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsTaxRoute: typeof SettingsTaxRoute
  SettingsTerminalsRoute: typeof SettingsTerminalsRoute
  SettingsTypeRoute: typeof SettingsTypeRoute
  SettingsUpdatesRoute: typeof SettingsUpdatesRoute
  SettingsVisibilityRoute: typeof SettingsVisibilityRoute
  SettingsWhatsappRoute: typeof SettingsWhatsappRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
  TransfersIdRoute: typeof TransfersIdRoute
  TransfersNewRoute: typeof TransfersNewRoute
  ReceivingIndexRoute: typeof ReceivingIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
  ApiPublicCashierLoginRoute: typeof ApiPublicCashierLoginRoute
  ApiPublicDesktopSessionRoute: typeof ApiPublicDesktopSessionRoute
  ApiPublicHealthMetadataRoute: typeof ApiPublicHealthMetadataRoute
  ApiPublicIdleTimeoutRoute: typeof ApiPublicIdleTimeoutRoute
  ApiPublicPosRulesRoute: typeof ApiPublicPosRulesRouteWithChildren
  ApiPublicSecurityAlertsRoute: typeof ApiPublicSecurityAlertsRoute
  ApiPublicStaffIdleTimeoutRoute: typeof ApiPublicStaffIdleTimeoutRoute
  ApiPublicSyncRoute: typeof ApiPublicSyncRoute
  ApiPublicSyncHealthRoute: typeof ApiPublicSyncHealthRoute
  ApiPublicTerminalPairingRoute: typeof ApiPublicTerminalPairingRoute
  ApiPublicTerminalStaffRoute: typeof ApiPublicTerminalStaffRoute
  ApiV1PosActivityPreferencesRoute: typeof ApiV1PosActivityPreferencesRoute
  ApiV1PosAuthorizationRoute: typeof ApiV1PosAuthorizationRoute
  ApiV1PosIpcAdoptRoute: typeof ApiV1PosIpcAdoptRoute
  ApiV1PosIpcAuthorizeRoute: typeof ApiV1PosIpcAuthorizeRoute
  ApiV1PosSyncRoute: typeof ApiV1PosSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-shops': {
      id: '/all-shops'
      path: '/all-shops'
      fullPath: '/all-shops'
      preLoaderRoute: typeof AllShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database-startup': {
      id: '/database-startup'
      path: '/database-startup'
      fullPath: '/database-startup'
      preLoaderRoute: typeof DatabaseStartupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holds': {
      id: '/holds'
      path: '/holds'
      fullPath: '/holds'
      preLoaderRoute: typeof HoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-hub': {
      id: '/inventory-hub'
      path: '/inventory-hub'
      fullPath: '/inventory-hub'
      preLoaderRoute: typeof InventoryHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-operations': {
      id: '/stock-operations'
      path: '/stock-operations'
      fullPath: '/stock-operations'
      preLoaderRoute: typeof StockOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifications': {
      id: '/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof VerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cashier-login': {
      id: '/api/cashier-login'
      path: '/api/cashier-login'
      fullPath: '/api/cashier-login'
      preLoaderRoute: typeof ApiCashierLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$tokenSlug': {
      id: '/c/$tokenSlug'
      path: '/c/$tokenSlug'
      fullPath: '/c/$tokenSlug'
      preLoaderRoute: typeof CTokenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$campaignSlug': {
      id: '/claim/$campaignSlug'
      path: '/claim/$campaignSlug'
      fullPath: '/claim/$campaignSlug'
      preLoaderRoute: typeof ClaimCampaignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/general-booking': {
      id: '/pos/general-booking'
      path: '/pos/general-booking'
      fullPath: '/pos/general-booking'
      preLoaderRoute: typeof PosGeneralBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/racket-service': {
      id: '/pos/racket-service'
      path: '/pos/racket-service'
      fullPath: '/pos/racket-service'
      preLoaderRoute: typeof PosRacketServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving/': {
      id: '/receiving/'
      path: '/receiving'
      fullPath: '/receiving/'
      preLoaderRoute: typeof ReceivingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving/$id': {
      id: '/receiving/$id'
      path: '/receiving/$id'
      fullPath: '/receiving/$id'
      preLoaderRoute: typeof ReceivingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/activity': {
      id: '/reports/activity'
      path: '/reports/activity'
      fullPath: '/reports/activity'
      preLoaderRoute: typeof ReportsActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/analytics': {
      id: '/reports/analytics'
      path: '/reports/analytics'
      fullPath: '/reports/analytics'
      preLoaderRoute: typeof ReportsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/business': {
      id: '/reports/business'
      path: '/reports/business'
      fullPath: '/reports/business'
      preLoaderRoute: typeof ReportsBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/catalog': {
      id: '/reports/catalog'
      path: '/reports/catalog'
      fullPath: '/reports/catalog'
      preLoaderRoute: typeof ReportsCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/coupons': {
      id: '/reports/coupons'
      path: '/reports/coupons'
      fullPath: '/reports/coupons'
      preLoaderRoute: typeof ReportsCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/history': {
      id: '/reports/history'
      path: '/reports/history'
      fullPath: '/reports/history'
      preLoaderRoute: typeof ReportsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/items': {
      id: '/reports/items'
      path: '/reports/items'
      fullPath: '/reports/items'
      preLoaderRoute: typeof ReportsItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/notifications': {
      id: '/reports/notifications'
      path: '/reports/notifications'
      fullPath: '/reports/notifications'
      preLoaderRoute: typeof ReportsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/payments': {
      id: '/reports/payments'
      path: '/reports/payments'
      fullPath: '/reports/payments'
      preLoaderRoute: typeof ReportsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/stock': {
      id: '/reports/stock'
      path: '/reports/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof ReportsStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/voids': {
      id: '/reports/voids'
      path: '/reports/voids'
      fullPath: '/reports/voids'
      preLoaderRoute: typeof ReportsVoidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/access': {
      id: '/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof SettingsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/accounts': {
      id: '/settings/accounts'
      path: '/settings/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof SettingsAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/booking-rules': {
      id: '/settings/booking-rules'
      path: '/settings/booking-rules'
      fullPath: '/settings/booking-rules'
      preLoaderRoute: typeof SettingsBookingRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/booking-slip': {
      id: '/settings/booking-slip'
      path: '/settings/booking-slip'
      fullPath: '/settings/booking-slip'
      preLoaderRoute: typeof SettingsBookingSlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/branch-telemetry': {
      id: '/settings/branch-telemetry'
      path: '/settings/branch-telemetry'
      fullPath: '/settings/branch-telemetry'
      preLoaderRoute: typeof SettingsBranchTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/catalog': {
      id: '/settings/catalog'
      path: '/settings/catalog'
      fullPath: '/settings/catalog'
      preLoaderRoute: typeof SettingsCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/data-sync': {
      id: '/settings/data-sync'
      path: '/settings/data-sync'
      fullPath: '/settings/data-sync'
      preLoaderRoute: typeof SettingsDataSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/database': {
      id: '/settings/database'
      path: '/settings/database'
      fullPath: '/settings/database'
      preLoaderRoute: typeof SettingsDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/database-explorer': {
      id: '/settings/database-explorer'
      path: '/settings/database-explorer'
      fullPath: '/settings/database-explorer'
      preLoaderRoute: typeof SettingsDatabaseExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/settings/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/settings/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/elements': {
      id: '/settings/elements'
      path: '/settings/elements'
      fullPath: '/settings/elements'
      preLoaderRoute: typeof SettingsElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/groups': {
      id: '/settings/groups'
      path: '/settings/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof SettingsGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/hardware': {
      id: '/settings/hardware'
      path: '/settings/hardware'
      fullPath: '/settings/hardware'
      preLoaderRoute: typeof SettingsHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/identity': {
      id: '/settings/identity'
      path: '/settings/identity'
      fullPath: '/settings/identity'
      preLoaderRoute: typeof SettingsIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/inheritance': {
      id: '/settings/inheritance'
      path: '/settings/inheritance'
      fullPath: '/settings/inheritance'
      preLoaderRoute: typeof SettingsInheritanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/lines': {
      id: '/settings/lines'
      path: '/settings/lines'
      fullPath: '/settings/lines'
      preLoaderRoute: typeof SettingsLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/logic-health': {
      id: '/settings/logic-health'
      path: '/settings/logic-health'
      fullPath: '/settings/logic-health'
      preLoaderRoute: typeof SettingsLogicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mobile-terminals': {
      id: '/settings/mobile-terminals'
      path: '/settings/mobile-terminals'
      fullPath: '/settings/mobile-terminals'
      preLoaderRoute: typeof SettingsMobileTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/numbering': {
      id: '/settings/numbering'
      path: '/settings/numbering'
      fullPath: '/settings/numbering'
      preLoaderRoute: typeof SettingsNumberingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/settings/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/payment-methods': {
      id: '/settings/payment-methods'
      path: '/settings/payment-methods'
      fullPath: '/settings/payment-methods'
      preLoaderRoute: typeof SettingsPaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/printer': {
      id: '/settings/printer'
      path: '/settings/printer'
      fullPath: '/settings/printer'
      preLoaderRoute: typeof SettingsPrinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/qr': {
      id: '/settings/qr'
      path: '/settings/qr'
      fullPath: '/settings/qr'
      preLoaderRoute: typeof SettingsQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/receipt-designer': {
      id: '/settings/receipt-designer'
      path: '/settings/receipt-designer'
      fullPath: '/settings/receipt-designer'
      preLoaderRoute: typeof SettingsReceiptDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/region': {
      id: '/settings/region'
      path: '/settings/region'
      fullPath: '/settings/region'
      preLoaderRoute: typeof SettingsRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rules': {
      id: '/settings/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof SettingsRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security-alerts': {
      id: '/settings/security-alerts'
      path: '/settings/security-alerts'
      fullPath: '/settings/security-alerts'
      preLoaderRoute: typeof SettingsSecurityAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/services': {
      id: '/settings/services'
      path: '/settings/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof SettingsServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sessions': {
      id: '/settings/sessions'
      path: '/settings/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shift-alerts': {
      id: '/settings/shift-alerts'
      path: '/settings/shift-alerts'
      fullPath: '/settings/shift-alerts'
      preLoaderRoute: typeof SettingsShiftAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sku': {
      id: '/settings/sku'
      path: '/settings/sku'
      fullPath: '/settings/sku'
      preLoaderRoute: typeof SettingsSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/stock-numbering': {
      id: '/settings/stock-numbering'
      path: '/settings/stock-numbering'
      fullPath: '/settings/stock-numbering'
      preLoaderRoute: typeof SettingsStockNumberingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/settings/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tax': {
      id: '/settings/tax'
      path: '/settings/tax'
      fullPath: '/settings/tax'
      preLoaderRoute: typeof SettingsTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/terminals': {
      id: '/settings/terminals'
      path: '/settings/terminals'
      fullPath: '/settings/terminals'
      preLoaderRoute: typeof SettingsTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/type': {
      id: '/settings/type'
      path: '/settings/type'
      fullPath: '/settings/type'
      preLoaderRoute: typeof SettingsTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/updates': {
      id: '/settings/updates'
      path: '/settings/updates'
      fullPath: '/settings/updates'
      preLoaderRoute: typeof SettingsUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/visibility': {
      id: '/settings/visibility'
      path: '/settings/visibility'
      fullPath: '/settings/visibility'
      preLoaderRoute: typeof SettingsVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/whatsapp': {
      id: '/settings/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof SettingsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/settings/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/$id': {
      id: '/transfers/$id'
      path: '/transfers/$id'
      fullPath: '/transfers/$id'
      preLoaderRoute: typeof TransfersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/new': {
      id: '/transfers/new'
      path: '/transfers/new'
      fullPath: '/transfers/new'
      preLoaderRoute: typeof TransfersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashier-login': {
      id: '/api/public/cashier-login'
      path: '/api/public/cashier-login'
      fullPath: '/api/public/cashier-login'
      preLoaderRoute: typeof ApiPublicCashierLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop-session': {
      id: '/api/public/desktop-session'
      path: '/api/public/desktop-session'
      fullPath: '/api/public/desktop-session'
      preLoaderRoute: typeof ApiPublicDesktopSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-metadata': {
      id: '/api/public/health-metadata'
      path: '/api/public/health-metadata'
      fullPath: '/api/public/health-metadata'
      preLoaderRoute: typeof ApiPublicHealthMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/idle-timeout': {
      id: '/api/public/idle-timeout'
      path: '/api/public/idle-timeout'
      fullPath: '/api/public/idle-timeout'
      preLoaderRoute: typeof ApiPublicIdleTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pos-rules': {
      id: '/api/public/pos-rules'
      path: '/api/public/pos-rules'
      fullPath: '/api/public/pos-rules'
      preLoaderRoute: typeof ApiPublicPosRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/security-alerts': {
      id: '/api/public/security-alerts'
      path: '/api/public/security-alerts'
      fullPath: '/api/public/security-alerts'
      preLoaderRoute: typeof ApiPublicSecurityAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-idle-timeout': {
      id: '/api/public/staff-idle-timeout'
      path: '/api/public/staff-idle-timeout'
      fullPath: '/api/public/staff-idle-timeout'
      preLoaderRoute: typeof ApiPublicStaffIdleTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync': {
      id: '/api/public/sync'
      path: '/api/public/sync'
      fullPath: '/api/public/sync'
      preLoaderRoute: typeof ApiPublicSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-health': {
      id: '/api/public/sync-health'
      path: '/api/public/sync-health'
      fullPath: '/api/public/sync-health'
      preLoaderRoute: typeof ApiPublicSyncHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/terminal-pairing': {
      id: '/api/public/terminal-pairing'
      path: '/api/public/terminal-pairing'
      fullPath: '/api/public/terminal-pairing'
      preLoaderRoute: typeof ApiPublicTerminalPairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/terminal-staff': {
      id: '/api/public/terminal-staff'
      path: '/api/public/terminal-staff'
      fullPath: '/api/public/terminal-staff'
      preLoaderRoute: typeof ApiPublicTerminalStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pos-rules/save': {
      id: '/api/public/pos-rules/save'
      path: '/save'
      fullPath: '/api/public/pos-rules/save'
      preLoaderRoute: typeof ApiPublicPosRulesSaveRouteImport
      parentRoute: typeof ApiPublicPosRulesRoute
    }
    '/api/v1/pos/activity-preferences': {
      id: '/api/v1/pos/activity-preferences'
      path: '/api/v1/pos/activity-preferences'
      fullPath: '/api/v1/pos/activity-preferences'
      preLoaderRoute: typeof ApiV1PosActivityPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pos/authorization': {
      id: '/api/v1/pos/authorization'
      path: '/api/v1/pos/authorization'
      fullPath: '/api/v1/pos/authorization'
      preLoaderRoute: typeof ApiV1PosAuthorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pos/ipc-adopt': {
      id: '/api/v1/pos/ipc-adopt'
      path: '/api/v1/pos/ipc-adopt'
      fullPath: '/api/v1/pos/ipc-adopt'
      preLoaderRoute: typeof ApiV1PosIpcAdoptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pos/ipc-authorize': {
      id: '/api/v1/pos/ipc-authorize'
      path: '/api/v1/pos/ipc-authorize'
      fullPath: '/api/v1/pos/ipc-authorize'
      preLoaderRoute: typeof ApiV1PosIpcAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pos/sync': {
      id: '/api/v1/pos/sync'
      path: '/api/v1/pos/sync'
      fullPath: '/api/v1/pos/sync'
      preLoaderRoute: typeof ApiV1PosSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicPosRulesRouteChildren {
  ApiPublicPosRulesSaveRoute: typeof ApiPublicPosRulesSaveRoute
}

const ApiPublicPosRulesRouteChildren: ApiPublicPosRulesRouteChildren = {
  ApiPublicPosRulesSaveRoute: ApiPublicPosRulesSaveRoute,
}

const ApiPublicPosRulesRouteWithChildren =
  ApiPublicPosRulesRoute._addFileChildren(ApiPublicPosRulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AllShopsRoute: AllShopsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BookingsRoute: BookingsRoute,
  CouponsRoute: CouponsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DatabaseStartupRoute: DatabaseStartupRoute,
  DisplayRoute: DisplayRoute,
  HoldsRoute: HoldsRoute,
  InventoryRoute: InventoryRoute,
  InventoryHubRoute: InventoryHubRoute,
  JoinRoute: JoinRoute,
  MembersRoute: MembersRoute,
  MembershipRoute: MembershipRoute,
  PromotionsRoute: PromotionsRoute,
  PurchasingRoute: PurchasingRoute,
  ReceiptsRoute: ReceiptsRoute,
  RecoveryRoute: RecoveryRoute,
  SalesRoute: SalesRoute,
  ShiftsRoute: ShiftsRoute,
  StaffRoute: StaffRoute,
  StockOperationsRoute: StockOperationsRoute,
  StoresRoute: StoresRoute,
  SuppliersRoute: SuppliersRoute,
  VerificationsRoute: VerificationsRoute,
  ApiCashierLoginRoute: ApiCashierLoginRoute,
  CTokenSlugRoute: CTokenSlugRoute,
  ClaimCampaignSlugRoute: ClaimCampaignSlugRoute,
  PosGeneralBookingRoute: PosGeneralBookingRoute,
  PosRacketServiceRoute: PosRacketServiceRoute,
  ReceivingIdRoute: ReceivingIdRoute,
  ReportsActivityRoute: ReportsActivityRoute,
  ReportsAnalyticsRoute: ReportsAnalyticsRoute,
  ReportsBusinessRoute: ReportsBusinessRoute,
  ReportsCatalogRoute: ReportsCatalogRoute,
  ReportsCouponsRoute: ReportsCouponsRoute,
  ReportsHistoryRoute: ReportsHistoryRoute,
  ReportsItemsRoute: ReportsItemsRoute,
  ReportsNotificationsRoute: ReportsNotificationsRoute,
  ReportsPaymentsRoute: ReportsPaymentsRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  ReportsStockRoute: ReportsStockRoute,
  ReportsVoidsRoute: ReportsVoidsRoute,
  RequestsIdRoute: RequestsIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  SettingsAccessRoute: SettingsAccessRoute,
  SettingsAccountsRoute: SettingsAccountsRoute,
  SettingsBookingRulesRoute: SettingsBookingRulesRoute,
  SettingsBookingSlipRoute: SettingsBookingSlipRoute,
  SettingsBranchTelemetryRoute: SettingsBranchTelemetryRoute,
  SettingsCatalogRoute: SettingsCatalogRoute,
  SettingsDataSyncRoute: SettingsDataSyncRoute,
  SettingsDatabaseRoute: SettingsDatabaseRoute,
  SettingsDatabaseExplorerRoute: SettingsDatabaseExplorerRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsDisplayRoute: SettingsDisplayRoute,
  SettingsElementsRoute: SettingsElementsRoute,
  SettingsGroupsRoute: SettingsGroupsRoute,
  SettingsHardwareRoute: SettingsHardwareRoute,
  SettingsIdentityRoute: SettingsIdentityRoute,
  SettingsInheritanceRoute: SettingsInheritanceRoute,
  SettingsLinesRoute: SettingsLinesRoute,
  SettingsLogicHealthRoute: SettingsLogicHealthRoute,
  SettingsMobileTerminalsRoute: SettingsMobileTerminalsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsNumberingRoute: SettingsNumberingRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsPaymentMethodsRoute: SettingsPaymentMethodsRoute,
  SettingsPrinterRoute: SettingsPrinterRoute,
  SettingsQrRoute: SettingsQrRoute,
  SettingsReceiptDesignerRoute: SettingsReceiptDesignerRoute,
  SettingsRegionRoute: SettingsRegionRoute,
  SettingsRulesRoute: SettingsRulesRoute,
  SettingsSecurityAlertsRoute: SettingsSecurityAlertsRoute,
  SettingsServicesRoute: SettingsServicesRoute,
  SettingsSessionsRoute: SettingsSessionsRoute,
  SettingsShiftAlertsRoute: SettingsShiftAlertsRoute,
  SettingsSkuRoute: SettingsSkuRoute,
  SettingsStockNumberingRoute: SettingsStockNumberingRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsTaxRoute: SettingsTaxRoute,
  SettingsTerminalsRoute: SettingsTerminalsRoute,
  SettingsTypeRoute: SettingsTypeRoute,
  SettingsUpdatesRoute: SettingsUpdatesRoute,
  SettingsVisibilityRoute: SettingsVisibilityRoute,
  SettingsWhatsappRoute: SettingsWhatsappRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
  TransfersIdRoute: TransfersIdRoute,
  TransfersNewRoute: TransfersNewRoute,
  ReceivingIndexRoute: ReceivingIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransfersIndexRoute: TransfersIndexRoute,
  ApiPublicCashierLoginRoute: ApiPublicCashierLoginRoute,
  ApiPublicDesktopSessionRoute: ApiPublicDesktopSessionRoute,
  ApiPublicHealthMetadataRoute: ApiPublicHealthMetadataRoute,
  ApiPublicIdleTimeoutRoute: ApiPublicIdleTimeoutRoute,
  ApiPublicPosRulesRoute: ApiPublicPosRulesRouteWithChildren,
  ApiPublicSecurityAlertsRoute: ApiPublicSecurityAlertsRoute,
  ApiPublicStaffIdleTimeoutRoute: ApiPublicStaffIdleTimeoutRoute,
  ApiPublicSyncRoute: ApiPublicSyncRoute,
  ApiPublicSyncHealthRoute: ApiPublicSyncHealthRoute,
  ApiPublicTerminalPairingRoute: ApiPublicTerminalPairingRoute,
  ApiPublicTerminalStaffRoute: ApiPublicTerminalStaffRoute,
  ApiV1PosActivityPreferencesRoute: ApiV1PosActivityPreferencesRoute,
  ApiV1PosAuthorizationRoute: ApiV1PosAuthorizationRoute,
  ApiV1PosIpcAdoptRoute: ApiV1PosIpcAdoptRoute,
  ApiV1PosIpcAuthorizeRoute: ApiV1PosIpcAuthorizeRoute,
  ApiV1PosSyncRoute: ApiV1PosSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
